### PR TITLE
TestScheduler delay behavior test

### PR DESCRIPTION
**Pull request by trevjonez**
Would be great if time based operator tests could make full use of TestScheduler delay skipping behavior.

If I remove the Unconfined override everything but legacy JS passes.
image

```patch
Index: src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt b/src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt
--- a/src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt	(revision 55b82684930ae9a67e53e57e632c3bb640b474f8)
+++ b/src/commonMain/kotlin/app/cash/turbine/FlowTurbine.kt	(date 1652572185509)
@@ -140,7 +140,7 @@
 private fun <T> Flow<T>.collectTurbineIn(scope: CoroutineScope): ChannelBasedFlowTurbine<T> {
   val events = Channel<Event<T>>(UNLIMITED)
 
-  val collectJob = scope.launch(start = UNDISPATCHED, context = Unconfined) {
+  val collectJob = scope.launch(start = UNDISPATCHED) {
     val terminalEvent = try {
       if (debug) println("Collect starting!")
       collect { item ->
```

### CODE REVIEW

**Comment by JakeWharton** [comment]
Yeah `runTest` seems to have wholly broken otherwise-valid `Unconfined` dispatcher usage. I think I need to isolate a sample and report it upstream.

That being said, removing it is safe for Turbine, it's just unfortunate as we incur double dispatch.

**Comment by trevjonez** [comment]
> safe for Turbine

Any idea what the wider spread impact on legacy JS would be? Those 4 failing tests seem like some very devious gaps. Or could we assume those on legacy JS are also willing to accept being stuck with legacy turbine?

Edit: even if you report upstream in an isolated helpful manner, would they do anything? It seems fairly documented that path has been abandoned.

**Comment by JakeWharton** [comment]
Unconfined is abandoned?

**Comment by JakeWharton** [comment]
Also we can drop legacy JS. We almost did for the most recent release but I made it work and reverted the removal.

**Comment by trevjonez** [comment]
> Unconfined is abandoned?

No sorry I wasn't clear. Legacy JS.

I'll update the PR with the changes.

**Comment by trevjonez** [comment]
Alright rebased and fixed imports to match.

**Comment by trevjonez** [comment]
Down to just a `TestScheduler` integration test after that last rebase. Still a fit for the project?

**Comment by JakeWharton** [comment]
So this is just a regression test now, right? The library itself is fixed.

**Comment by JakeWharton** [comment]
Or maybe not as the CI indicates...

**Pull request closed without merging**
