### PR TITLE
Default timeout increase

### PR DESCRIPTION
**Pull request by trevjonez**
Follow up to #199

### CODE REVIEW

**Comment by JakeWharton** [comment]
There are tests which validate the default timeout which will need updated.

**Comment by trevjonez** [comment]
Alright tests updated and I just ran it against the consumer via composite build to validate the 3 seconds provides enough headroom. Tests are going brrrr again.

image

**Comment by JakeWharton** [comment]
@jingibus you okay with this?

**Comment by trevjonez** [comment]
Looking into the JS test failures now..
```

Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/tjones/Source/turbine/build/js/packages/turbine-test/adapter-nodejs.js)
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/tjones/Source/turbine/build/js/packages/turbine-test/adapter-nodejs.js)
	at <global>.listOnTimeout(node:internal/timers:557)
	at <global>.processTimers(node:internal/timers:500)

```

**Comment by JakeWharton** [comment]
Yeah you need to bump the JS runner's timeout as it defaults to 2 seconds.

**Comment by jingibus** [comment]
Sure? It should be short enough that, if I've written a failing test and
iterating on it, it's not too painful to rerun. 2s might get painful if
I've made a change that breaks a whole suite, but on single test failures
that is fine.

It is surprising to me that 1s is not long enough, even on CI. But I am out
of pocket atm and can't familiarize myself with your circumstances.

It might be nice to be able to change this more easily on CI vs local.

**Comment by trevjonez** [comment]
> Yeah you need to bump the JS runner's timeout as it defaults to 2 seconds.

I was digging around for a bit and found absolutely nothing I could adjust. Disclaimer being I am completely new to the kotlin/js world. What did I miss?

**Comment by JakeWharton** [comment]
It's doable in the DSL. The test runner is Mocha and there's some way to alter its timeout. I can look when I'm at a computer at some point...

**Comment by trevjonez** [comment]
> It's doable in the DSL. The test runner is Mocha and there's some way to alter its timeout. I can look when I'm at a computer at some point...

Went digging thru the DSL sources and found it thank you. Going to push again then clone on the macbook to check that all those targets can pass.

> It might be nice to be able to change this more easily on CI vs local.

It would be super nice if we could rig it to pull the default from the runtime env similar to how coroutines controls parallelism. `"kotlinx.coroutines.io.parallelism"`

Is there already a good expect/actual solution for that sort of thing we could employ here?

**Comment by JakeWharton** [comment]
The value of the timeout is already configurable through a runtime API whereas the IO parallelism is not. I do not think we need to expose the default as something configurable.

**Pull request merged**
