### PR TITLE
[FEAT] Support wasm

### PR DESCRIPTION
**Pull request by ahna92**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Once a stable version of coroutines is out we'd be happy to mirror their new targets.

**Comment by ahna92** [comment]
@JakeWharton sure 👍 , is it possible to get an alpha/canary version with this change ?

**Comment by JakeWharton** [comment]
I'm on paternity leave and it's the holidays. I also don't want to really set a precedent. We can merge it and you can consume the snapshot. I'll look tomorrow.

**Comment by ahna92** [comment]
@JakeWharton nothing urgent, if it's a click of button let's have it , if not just enjoy the holidays ! can look at this next year :D

**Comment by faogustavo** [comment]
Now that Coroutines 1.8.0 is stable and merged into the trunk, would you be able to move forward with this? :)

**Comment by JakeWharton** [comment]
Yes. Please rebase. Do they only support wasmJs or was wasmWasi also included?

**Comment by faogustavo** [comment]
Looks like only [WasmJS](https://github.com/Kotlin/kotlinx.coroutines/blob/master/buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts#L57).

**Pull request merged**
